sudo: required
language: node_js
node_js:
  - 10
dist: trusty
jobs:
  include:
    - stage: deploy to staging
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: "c+83paLIJWreBcZ1BRszZF4SOcEdeUbohfiJjMMSHnxgod4UaQzanEczIhJJzUsM6M5SZpz1FD2AKxkvU0VcKgieZT0cO4iqB39V+CZNs5vykwQOsy4z4VsbtdFqhMMHPJy07IvrSXQs/zAZBDZbq1IDxkSjFLcydU+sZKJHVk5tA62RPFQ9Ja+oTb7mWgwWTeFyFFkPNkDVEIrbL6+wY0koHUaFGsZmykVIpA1JknTNEjey+g9EmNpjsRfrXFSfm2cKhCD3Y70323M7n5T+VlcdrTgQ9pSIc/ZrcH44JSjBd1mpBwIoDOYvCToY/boKkEy2LwJc6XTVrZEtrQMWVw3HHr2ds7XaHiCv+IM0imp0P6Qd4sTj1+8qBRf0F2jUtm9re4crtQRJg0rz5p34g7T/m5z9obSZwVFmbhswMOCdAR8ftvv/bo6xuNWl3tYVZsEFqOh/El58ve2e0jZJcCMV31sNYweABDWG3QvwDunRYhvpUvnUWpjhhojjgLkKpaPHIARJsClxJXzaXn4gf6uCtkqYDZc2Xricy9neKTLSIxtJBOkjvqEIfORyzVggpNN5Lzo+wGSJyo2aiyfrO2I9Zup8nWAl30gd3SRdxzlqu48T0BwrXYP9YYw58ANMLO0XjwHiQETU/PjDtXs+fA6gYfqebYbhqNKYsLGlagI="
    - stage: test staging
      script: 'curl https://travis-ci-selenium-test.herokuapp.com/'
      script: 'npm run test'
before_install:
  - npm install
addons:
  sauce_connect:
    username: JohannC
    access_key:
      secure: "jrSvXK0P7Dr2A3wj6VeEj+RT1FvMXQJGUDYrY15VU/zM5Os+iFQ8JsDmw5D7tKu+n/rGNxwzDbHZz8j9jMe95e2rHFi0SJ9GQa4q0MS0SbEAo1pJByDY0qvbk9aVIoC3coq3mTLHxONOdpoOgFJa8UZ4GlSLy1fmgJ+2U0OChZOeYdKETUQfO9ttkFtmG5jK1IDygrpVb517ng7qboYGm3Zf6tyQ2PTVozPv2jyVmp+6T+mCjLIbmXH4jmJtLQRpvMh7vt1hLAvV+x4M4qs6WCUvBv8IPlAB0EdXtVCc1zk1UvZepZkUfbhgQTD25soQMhagbyAq03jfSP7Qa0wes0hUV6ZHO4n/lBmTwimBUGqF9nNw84ektJ3PjqIfCCdssrNqcLu1wDBlREEpWcA+UryhiKjIdpwLKekexUNC8/i17X+nO5ySNIOv8ct/xYB4FBC6alL6g4InG4JBLFI7yXTWj/2K8cjRzDJpwny88aFHoIsmPmMLz8zrCBWtIB4c11NG8b21rGsbmmF5/WRxdpEfHJaBhPhujd2bNULaFVwoggLXj4ySv3SQSj1SMTQKgmuqd6BdnBZuisOGJD4nHhkYbSEI1kgV899eHX4tVnOkpLs3CP8JAkhOKBBdo2+s5hmnz2i8/9UR3oiT35BB+zUHPKwkHFVoXmsnbv6jc4Q="