sudo: required
language: node_js
node_js:
- 10
dist: trusty
jobs:
  include:
  - stage: deploy to staging
    script: skip
    deploy:
      provider: heroku
      app: travis-ci-selenium-sauce-labs
      api_key:
        secure: c+83paLIJWreBcZ1BRszZF4SOcEdeUbohfiJjMMSHnxgod4UaQzanEczIhJJzUsM6M5SZpz1FD2AKxkvU0VcKgieZT0cO4iqB39V+CZNs5vykwQOsy4z4VsbtdFqhMMHPJy07IvrSXQs/zAZBDZbq1IDxkSjFLcydU+sZKJHVk5tA62RPFQ9Ja+oTb7mWgwWTeFyFFkPNkDVEIrbL6+wY0koHUaFGsZmykVIpA1JknTNEjey+g9EmNpjsRfrXFSfm2cKhCD3Y70323M7n5T+VlcdrTgQ9pSIc/ZrcH44JSjBd1mpBwIoDOYvCToY/boKkEy2LwJc6XTVrZEtrQMWVw3HHr2ds7XaHiCv+IM0imp0P6Qd4sTj1+8qBRf0F2jUtm9re4crtQRJg0rz5p34g7T/m5z9obSZwVFmbhswMOCdAR8ftvv/bo6xuNWl3tYVZsEFqOh/El58ve2e0jZJcCMV31sNYweABDWG3QvwDunRYhvpUvnUWpjhhojjgLkKpaPHIARJsClxJXzaXn4gf6uCtkqYDZc2Xricy9neKTLSIxtJBOkjvqEIfORyzVggpNN5Lzo+wGSJyo2aiyfrO2I9Zup8nWAl30gd3SRdxzlqu48T0BwrXYP9YYw58ANMLO0XjwHiQETU/PjDtXs+fA6gYfqebYbhqNKYsLGlagI=
  - stage: test staging
    script: npm run test
before_install:
- npm install
addons:
  sauce_connect:
    username: JohannC
    access_key:
      secure: jrSvXK0P7Dr2A3wj6VeEj+RT1FvMXQJGUDYrY15VU/zM5Os+iFQ8JsDmw5D7tKu+n/rGNxwzDbHZz8j9jMe95e2rHFi0SJ9GQa4q0MS0SbEAo1pJByDY0qvbk9aVIoC3coq3mTLHxONOdpoOgFJa8UZ4GlSLy1fmgJ+2U0OChZOeYdKETUQfO9ttkFtmG5jK1IDygrpVb517ng7qboYGm3Zf6tyQ2PTVozPv2jyVmp+6T+mCjLIbmXH4jmJtLQRpvMh7vt1hLAvV+x4M4qs6WCUvBv8IPlAB0EdXtVCc1zk1UvZepZkUfbhgQTD25soQMhagbyAq03jfSP7Qa0wes0hUV6ZHO4n/lBmTwimBUGqF9nNw84ektJ3PjqIfCCdssrNqcLu1wDBlREEpWcA+UryhiKjIdpwLKekexUNC8/i17X+nO5ySNIOv8ct/xYB4FBC6alL6g4InG4JBLFI7yXTWj/2K8cjRzDJpwny88aFHoIsmPmMLz8zrCBWtIB4c11NG8b21rGsbmmF5/WRxdpEfHJaBhPhujd2bNULaFVwoggLXj4ySv3SQSj1SMTQKgmuqd6BdnBZuisOGJD4nHhkYbSEI1kgV899eHX4tVnOkpLs3CP8JAkhOKBBdo2+s5hmnz2i8/9UR3oiT35BB+zUHPKwkHFVoXmsnbv6jc4Q=
env:
  matrix:
    - SAUCE_LABS_USERNAME=JohannC
    - secure: KzPE4kfu49xDMwFnG9tuoYmrwOjmx4DNK71iu23ghA1l5pPIbOba+uoLBteulcBixpq8AL7UZHt7aoNi92WtH2c1SvfaMnkbD9zwrCyE0nS4X9XAo02Ao4iAuD68q1hPNYb3x6kptzqW4prrjuyxe/lbaAlmpaogkDEGstDrXc5qCjaJ16B9krqsp8VPH9NUcBABQJM7XGwgU07uKGgwhkgJWsvBVnrv7VdIiFGGmZFs4sJuFJrBClsXRshoF2ps5PTGSCtscyfyZShZ/hQn//9wL03hURdqA2TAIBve1oJ5KMoZrxmsyLX1xLVk/ucvxpsOvLiAdIeGQZxeKpG2eH7WGdCcBWBsgfqvRRf81ziPWy6T5/lB9R0Gz3WMjP/ti1ciJPudbztbxb3lIG2AMtYO0CXsKxCmKuo3FBpJHdTWiTvPQBX6zO9IGo6+Jw2X44QQFx6dOwqW0vdO3FDV/JMkeItMdlN1zS3VyI2d98m7qLiq8A89XMA4f74P1k9QQSULZWnzxsw6ddzrUscn4+R6VSSvnA7tsdJnLt9W7J38ZoYxJcy69Gp5knAQ7j9M6F512XmOXjrPCGLsEU0yc4+ofRdMFNWY1Pfn0mHMnEIo5s2H8AOQ6D6CNf+R3SwFMYL3rJJ/whZwimztzrpA46Dm1YindPntqI3jdUnY47w=
