sudo: required
language: node_js
node_js:
  - 10
dist: trusty

before_script:
  - sleep 2 # give Web server some time to bind to sockets, etc
jobs:
  include:
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: "fh7ozFzY3X4bwoPh0vTIZriMJvVbb1bJvXI7pTtwY/CnUVc6TuU5nYtm2AZDIAVqkr4ku7iKIqjEpGq4H5KuXeFja1zxpspAUu//VqT0q2mlBFXwMZmGHaDyu8+nzIXu0LwMRQZzy24VbTwE8yvjENtDdqFG3ZEJxfhjGVMKyoJjFVT6F0wQSopoIKr4rEc6bTxtbE9nrm2cqfuHYgR6aJXG8lDkAg6ljcJi0Tr7uYe/DPZMi7u4pMokKMBWvRTXJBJUhWaMgNsp4B/GUy4S5cFRvjWYj1EsLI65Ku064YSI45zdryRhaLdfrA4fPoDvnIfbIMpQ9kQnTpMPxvFRwg2wJbL+86huNP6WNLb7BU756lCsBXAmvaz30egtjC8zeF1fQVspRZKlad4kguSZCWZvI62ozZFdoFqOrAOY3xMLeLTNl/13CHm2KZmbe1RcFub+vkrAINmugBbYT7f3L49KGv/Id//L+aU25EeFvAlOcOq6djlDdmxd/V112kZ9csYOA+NMxHvkZyLzm+XjrlotQ6UiP7iXy0yRLZy3fT7nQ6z219gT1UEEqET0N/CPtJdfVhtqb05QcKxzV7oPQlxzxyjYDMjSkwzVfecpq+3ZAblK9y7w6Zt6nPD2vldBZYbHS+wZzLerf9k45hm4nrhgJMGkjG3jHtkW3+xHN40="
    - stage: test staging
      script: 'curl https://travis-ci-selenium-test.herokuapp.com/'
      script: 'npm run test'
before_install:
  - npm install
addons:
  sauce_connect:
    username: JohannC
    access_key:
      secure: "jrSvXK0P7Dr2A3wj6VeEj+RT1FvMXQJGUDYrY15VU/zM5Os+iFQ8JsDmw5D7tKu+n/rGNxwzDbHZz8j9jMe95e2rHFi0SJ9GQa4q0MS0SbEAo1pJByDY0qvbk9aVIoC3coq3mTLHxONOdpoOgFJa8UZ4GlSLy1fmgJ+2U0OChZOeYdKETUQfO9ttkFtmG5jK1IDygrpVb517ng7qboYGm3Zf6tyQ2PTVozPv2jyVmp+6T+mCjLIbmXH4jmJtLQRpvMh7vt1hLAvV+x4M4qs6WCUvBv8IPlAB0EdXtVCc1zk1UvZepZkUfbhgQTD25soQMhagbyAq03jfSP7Qa0wes0hUV6ZHO4n/lBmTwimBUGqF9nNw84ektJ3PjqIfCCdssrNqcLu1wDBlREEpWcA+UryhiKjIdpwLKekexUNC8/i17X+nO5ySNIOv8ct/xYB4FBC6alL6g4InG4JBLFI7yXTWj/2K8cjRzDJpwny88aFHoIsmPmMLz8zrCBWtIB4c11NG8b21rGsbmmF5/WRxdpEfHJaBhPhujd2bNULaFVwoggLXj4ySv3SQSj1SMTQKgmuqd6BdnBZuisOGJD4nHhkYbSEI1kgV899eHX4tVnOkpLs3CP8JAkhOKBBdo2+s5hmnz2i8/9UR3oiT35BB+zUHPKwkHFVoXmsnbv6jc4Q="